### ISSUE TITLE
[Bug] Throw invalid parameter format error when no charset property

### ISSUE THREAD

**Issue by HongjiangHuang** [jshttp/content-type#15]
### Examles
```
let headers = [
  'content-type': 'text/html;'
];

contentType.parse(headers['content-type']);
```

![image](https://user-images.githubusercontent.com/20190812/86288880-42434600-bc1d-11ea-9814-6ad5da8a496a.png)

But according to HTTP RFC, this is a legal content type.

**Comment by dougwilson** [comment]
The trailing semicolon is the invalid part; parameters start with a semicolon if you follow the ABNF in the standard, so that header looks like a parameter started but was just truncated.

**Comment by HongjiangHuang** [comment]
![image](https://user-images.githubusercontent.com/20190812/86290655-62283900-bc20-11ea-811b-ecb2ab09a134.png)

This is the original content-type
