### ISSUE TITLE
Black Duck reporting Thunderbird as a dependency to content-type npm package

### ISSUE THREAD

**Issue by gvp-adityachava** [jshttp/content-type#16]
Hi,

I have found that https://www.npmjs.com/package/content-type, the black duck is showing Thunderbird as a dependency and it is showing a license issue.

Can you confirm whether this package internally uses **ThunderBird**. 
In the index.js file or package.json file I could not find anywhere where this is used.
Looking forward for the help.

Regards
Aditya

**Comment by dougwilson** [comment]
I'm not sure what you mean by ThunderBird, but if it is https://www.thunderbird.net/en-US/ then no, this library does not use that, as this is a Node.js library which has zero dependencies. You can find our entire source code at https://github.com/jshttp/content-type/blob/master/index.js which does not use the `require` function to import any dependencies.
