### ISSUE TITLE
Invalid parameter format reading Amazon AVS multipart headers

### ISSUE THREAD

**Issue by Mnark** [jshttp/content-type#9]
I am using Amazon AVS, which is returning a content type header of ":"multipart/related; boundary=------abcde123; type=application/json".  The package throws a TypeError('invalid parameter format').

It appears to be the trailing "/json" which is causing the issue (manually removing it fixes the problem).

**Comment by dougwilson** [comment]
Hi @Mnark, that is because the `/` character is not a valid character that can exist in a parameter value outside of being inside quotes.

You can read more about the syntax for a `Content-Type` header in the specification: https://tools.ietf.org/html/rfc7231#section-3.1.1.1

**Comment by giautm** [comment]
Same issue here:
```
multipart/form-data; boundary=j.GjQoqKLZ0xYPH-ee/1EB4lWbCgBzn0zh/RR_5veCFZciFdbflJcXvDak6mvpfX.vYEy-
```

the `/` character is a valid character in `boundary` specification, so it no quoted.
https://tools.ietf.org/html/rfc2046#section-5.1.1
